import { mkdirSync, writeFileSync } from 'node:fs';

const out = `/* eslint-disable */
// Generated by packages/contracts/scripts/generate-types.mjs from schema/mesh-result-v1.schema.json.
// Do not edit by hand.

export type JobStageV1 =
  | 'queued'
  | 'downloading'
  | 'detecting'
  | 'tracking'
  | 'meshing'
  | 'skinning'
  | 'smoothing'
  | 'analyzing'
  | 'packaging'
  | 'complete'
  | 'failed';

export interface Vec2 { 0: number; 1: number; length: 2 }
export type Vec3 = [number, number, number];
export type Quaternion = [number, number, number, number];
export type Mat4 = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

export interface MeshResultV1 {
  schema_version: 'mesh-result-v1';
  video: VideoMetadataV1;
  people: PersonV1[];
  frames: FrameV1[];
  analysis: AnalysisV1;
  assets: AssetManifestV1;
  model_report: ModelReportV1;
}

export interface VideoMetadataV1 {
  source_url: string;
  playback_url: string;
  duration_seconds: number;
  fps: number;
  dimensions: { width: number; height: number };
}

export interface PersonV1 {
  track_id: string;
  color: string;
  confidence: number;
  visible_frame_ranges: Array<[number, number]>;
  primary_dancer_score: number;
  mesh_asset: MeshAssetV1 | null;
  error?: string;
}

export interface MeshAssetV1 {
  asset_id: string;
  format: 'inline-rest-mesh-v1';
  vertices: Vec3[];
  normals: Vec3[];
  faces: Array<[number, number, number]>;
  skin_weights: SkinWeightV1[];
  joint_hierarchy: JointV1[];
  inverse_bind_matrices: Mat4[];
  shape_parameters: ShapeParametersV1;
  source_model: string;
}

export interface SkinWeightV1 {
  joints: number[];
  weights: number[];
}

export interface JointV1 {
  name: string;
  parent_index: number | null;
  rest_position: Vec3;
}

export interface ShapeParametersV1 {
  height_m: number;
  shoulder_width_m: number;
  hip_width_m: number;
  body_shape_coefficients: number[];
}

export interface FrameV1 {
  frame_index: number;
  timestamp_seconds: number;
  people: PersonFrameV1[];
}

export interface PersonFrameV1 {
  track_id: string;
  bbox: [number, number, number, number];
  keypoints_2d: Keypoint2DV1[];
  joints_3d: JointPoseV1[];
  pose_params: number[];
  global_transform: TransformV1;
  visibility: number;
  tracking_confidence: number;
}

export interface Keypoint2DV1 {
  name: string;
  position: [number, number];
  confidence: number;
}

export interface JointPoseV1 {
  name: string;
  position: Vec3;
  rotation: Quaternion;
  confidence: number;
}

export interface TransformV1 {
  translation: Vec3;
  rotation: Quaternion;
  scale: Vec3;
}

export interface AnalysisV1 {
  beats: BeatV1[];
  difficulty: {
    overall_score: number;
    timeline: Array<{ timestamp_seconds: number; score: number }>;
    body_parts: Record<string, number>;
  };
  foot_contacts: FootContactV1[];
  path_trails: PathTrailV1[];
  step_segments: StepSegmentV1[];
}

export interface BeatV1 { timestamp_seconds: number; strength: number }
export interface FootContactV1 { track_id: string; foot: 'left' | 'right'; timestamp_seconds: number; contact: 'heel' | 'toe' | 'flat' | 'slide' | 'airborne'; confidence: number }
export interface PathTrailV1 { track_id: string; joint_name: string; points: Array<{ timestamp_seconds: number; position: Vec3 }> }
export interface StepSegmentV1 { label: string; start_seconds: number; end_seconds: number; difficulty: number; primary_body_part: string }

export interface AssetManifestV1 {
  mesh_asset_urls: Array<{ track_id: string; url: string; content_type: string }>;
  glb_url?: string;
  debug_overlay_urls: string[];
}

export interface ModelReportV1 {
  detector: ModelDescriptorV1;
  tracker: ModelDescriptorV1;
  mesh: ModelDescriptorV1;
  runtime_ms: number;
  warnings: string[];
  license_flags: LicenseFlagV1[];
}

export interface ModelDescriptorV1 { name: string; version: string; adapter: string; enabled: boolean }
export interface LicenseFlagV1 { component: string; license: string; commercial_use: 'allowed' | 'restricted' | 'unknown'; note: string }
`;

mkdirSync('src', { recursive: true });
writeFileSync('src/mesh-result-v1.ts', out);
